server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie
            - PreOauth2SSOGatewayFilter
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie
            - PreOauth2SSOGatewayFilter
        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/transaction/**
          filters:
            - RewritePath=/transaction/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie
            - PreOauth2SSOGatewayFilter
  security:
    oauth2:
      client:
        registration:
          uaa:
            client-id: online-shop
            client-secret: b994d1f8-ee6f-4bf8-b66b-87de5192ac34
            authorization-grant-type: client_credentials
        provider:
          uaa:
            token-uri: https://localhost:8444/oauth/token
