server:
  port: 8091

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
    data: classpath:/db/data.sql

  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console
      settings.web-allow-others: true